### PR TITLE
[Fabric] Updated to Minecraft 1.19.4

### PR DESCRIPTION
**Pull request by Xernium**
I am pretty sure the depth call on renderer is no longer required (not needed)
I kept pretty true to your forge 1.19.4 update.
Please test this again, but it works fine for me

### CODE REVIEW

**Comment by Xernium** [comment]
Found a renderer issue with another plugin, caused by my work here, investigating...

**Comment by Xernium** [comment]
Is related to JEI being broken (but I don't think it's caused by these edits), nonetheless 
https://pastes.dev/KxgQDnpu9u
and cause https://pastes.dev/FpjArlr1RA

**Comment by MrCrayfish** [comment]
Mod has already been updated in the `multiloader/1.19.X` branch (https://github.com/MrCrayfish/Configured/tree/multiloader/1.19.X)

**Comment by Xernium** [comment]
You did not update Configured for **Fabric** 1.19.4. This PR targeted the **Fabric** branch not the Forge branch.
If you didn't accept this will you at least update it yourself? It's broken on 1.19.4 and as obviously seen from the changes here the 1.19.3 version will not work correctly on .4

**Comment by Xernium** [comment]
If you could update the releases on curseforge then that'd be appreciated 

> Mod has already been updated in the `multiloader/1.19.X` branch (https://github.com/MrCrayfish/Configured/tree/multiloader/1.19.X)

**Pull request closed without merging**
