### PR TITLE
Update sv_se.json

### PR DESCRIPTION
**Pull request by Regnander**
Added the new string, removed color tags and made minor changes to the existing translation.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @Regnander, I am currently relicensing Configured to LGPLv3. I want to get your permission to change your contributions under this new license. Thank you.

**Comment by Regnander** [comment]
> Hey @Regnander, I am currently relicensing Configured to LGPLv3. I want to get your permission to change your contributions under this new license.

You have my permission to do so.

> Thank you.

Thank *you* for making awesome mods!

**Comment by MrCrayfish** [comment]
Thank you for the quick response.

**Pull request merged**
