### PR TITLE
Real Update to 1.20.1

### PR DESCRIPTION
**Pull request by remplerus**
Created an Update to 1.20.1 with multiloader. I had some problems to get Fabric to work tho. Added a TODO in ScreenMixin as it's breaking there and it's better if you're fixing that instead of me as I break everything related to mixins.

This superseeds #107

### CODE REVIEW

**Comment by PlayfulPiano** [comment]
Could you post a compiled jar for this?

**Comment by remplerus** [comment]
as long as i don't have any information from the code owner, i won't publish any kind of compiled jar files. Also to mention: now that Forge and NeoForge have devided in 1.20.2, there'll be some more tweaking in these multiloader. Need to investigate fabric problems too. So there's much work to do, going back to draft for now.

**Comment by remplerus** [comment]
I disabled mixins for now. Fabric version is running fine now. Haven't tested with multiple mods.

**Comment by PlayfulPiano** [comment]
just tried compiling and it gave a failure:
image

**Comment by remplerus** [comment]
Well you need a github token to enable downloading from github pkg.

**Comment by PlayfulPiano** [comment]
actually nvm I think I downloaded the wrong commit

**Comment by PlayfulPiano** [comment]
actually I think I downloaded the wrong commit but it still gave me a failed build error
image

**Comment by PlayfulPiano** [comment]
> Well you need a github token to enable downloading from github pkg.

oh, how would I get the token for this?

**Comment by Neroland** [comment]
@MrCrayfish - Please could we get the forge version?

**Comment by remplerus** [comment]
thanks for updating mrcrayfish :)

**Pull request closed without merging**
