### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by vanja-san**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @vanja-san, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

**Comment by vanja-san** [comment]
> Hey @vanja-san, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

No problems

**Comment by MrCrayfish** [comment]
Thanks for the quick response. I just want to clear up that when I said contributions in the original message I meant your contributions.

**Pull request merged**
