### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by TexBlock**
-  Fix the zh_cn typo （ #39 ）
-  Translation `"configured.config.client.force_configured_menu": "Force Configured Menu"`

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @TexBlock, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

**Comment by TexBlock** [comment]
> Hey @TexBlock, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

I agree to change the license to LGPLv3

**Comment by MrCrayfish** [comment]
Thanks for the quick response. I just want to clarify that when I said contributions in the previous reply, I meant your contributions. I made a typo.

**Pull request merged**
