### PR TITLE
Create de_de.json (german translation)

### PR DESCRIPTION
**Pull request by Krxwallo**
Translated  to german

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @Krxwallo, I am currently relicensing Configured to LGPLv3. I want to get your permission to change your contributions under this new license. Thank you.

**Comment by Krxwallo** [comment]
You have my permission.

**Comment by MrCrayfish** [comment]
Thank you for the quick response.

**Pull request merged**
