### PR TITLE
Update JEI config support

### PR DESCRIPTION
**Pull request by mezz**
I added some methods to JEI's API so that Configured can get the config information without reflection.
This should make the compatibility much more stable, since JEI does not change the API much.

~~There are some regressions here, like Configured does not understand my `record` values.~~
~~I added some extra support for enums in lists, but I wasn't able to make it use a selector like with regular enum values.~~

~~Despite the drawbacks, I hope this is a good clean starting point at least.~~

Update: I have added full support for serializing and deserializing these values in the configs.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
I am assuming that your `ini` format configs will adapt to your new config api?

**Comment by MrCrayfish** [comment]
Configured doesn't know how to convert records like `ColorName` into a `String` and vice versa. In my original implementation I added my own parser but that depended on the full codebase, since switching to API only of JEI this would no longer be possible.

**Comment by mezz** [comment]
Yeah, that is a drawback of my implementation here. 
I noted that in the PR description as the main regression from this PR.
I would like to think a bit more about how I could support that properly.

Here are some improvements that I think Configured could implement later to improve support for JEI's configs:
* do not allow editing values that are unknown, instead offer a link to open the config file
* improved editing of List<Enum>, so the player is provided an enum selection instead of a string entry.

**Comment by mezz** [comment]
I may be able to expose the string serialization and deserialization in JEI's API somehow. 
I will try some things out and see how it looks.

**Comment by mezz** [comment]
I have updated this PR, and now it uses new features of JEI's API to implement `IListType` for `ColorName`. 🎉

**Comment by mezz** [comment]
I have updated the PR to use the latest JEI version, which exposes configs much earlier.
This way, players can access all the JEI configs before entering a world.

**Comment by MrCrayfish** [comment]
Everything checks out. Merging now. Thanks for your work into making these mods compatible again.

**Comment by MrCrayfish** [comment]
Hey @mezz, I am currently relicensing Configured. I want to change the mod to be under a more appropriate license of LGPLv3.
I want to get your permission to change the license of your contributions under this new license. Thank you.

**Comment by mezz** [comment]
Hello! You have my permission to relicense my changes to Configured under LGPLv3 :+1:

**Comment by MrCrayfish** [comment]
Thank you!

**Pull request merged**
