### PR TITLE
Added Italian Translation

### PR DESCRIPTION
**Pull request by Insane96**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thnak you!

**Comment by MrCrayfish** [comment]
Hey @Insane96, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

**Comment by Insane96** [comment]
Uhm, sure I guess

**Comment by MrCrayfish** [comment]
Thanks for the quick response. Even though it's translations, I still need to get your permission to change the license of it.

**Comment by MrCrayfish** [comment]
I just want to clarify when I said contributions in the initial message, I meant your contributions. I just want to clear this up.

**Pull request merged**
