### PR TITLE
full translation uk_ua.json

### PR DESCRIPTION
**Pull request by MEGATREX4**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @SKZGx, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

**Comment by MEGATREX4** [comment]
Yes, of course, no problem
thank you for your hard work, my team and I adore your mods <3

**Comment by MrCrayfish** [comment]
Thanks for the quick response.

**Comment by MrCrayfish** [comment]
I just want to clarify when I said contributions in the initial message, I meant your contributions. I just want to clear this up.

**Comment by MEGATREX4** [comment]
Yeah, yeah, I get it, just thought I'd say thanks <3

**Pull request merged**
