### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by JoseDeFreitas**
Hello! I found this repository and saw there are translations for other languages. I decided to translate it to my native language (Spanish) from the English strings. If anything, let me know.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Hey @JoseDeFreitas, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

**Comment by JoseDeFreitas** [comment]
Hello, @MrCrayfish. Sure, you have my permission. Have a great day.

**Comment by MrCrayfish** [comment]
Thanks for the quick response.

**Comment by MrCrayfish** [comment]
I just want to clarify when I said contributions, I meant your contributions. I just want clear that up.

**Pull request merged**
