### PR TITLE
Added Custom Mod Config Support.

### PR DESCRIPTION
**Pull request by Speiger**
o/

This was a bit more work then expected.
I basically tore your mod apart and stitched it back together.

99% of forge dependencies are basically removed from this mod.
The only thing that's left inside of the mod that requires forge is the sync with server.
This has to be implemented by the person who wants to implement their custom config format anyways so that is fine.

Everything works now through "IModConfig", which basically creates a IConfigEntry (that is your IEntry) and these entries are auto converted to the elements that need them.

This whole refactor also cleaned up the code quite a bit because i was able to simplify a lot of the existing code.

I created a "api" folder which contains all the classes custom configs will need to create their stuff.
And also a helper class that allows to create custom Config Backgrounds without having to search through your mod.

Ofcourse you don't have to accept this patch but I thought I help out since this is kinda my strength in programming.

I tested a bit of things but I expect this not to be a flawless patch that still will require edge case fixes.
But everything that could be tested in singleplayer worked fine without a worry.
And I mostly moved code around and not change to much.

Also I plugged myself a tiny bit with Authors in the javaDoc.

Hope that helps.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
I've breifly look over your code and it looks great, very readable. I'll take a deeper look so and provide any feedback (if any). It's likely that this will be merged.

**Comment by Speiger** [comment]
Any Updated on this?
Because I kinda want to integrate that on the ic2c port to 1.16 (that is going to be ported to 1.18 too)
So configured works with it too.

**Comment by MrCrayfish** [comment]
I've finally taken a closer look at this PR. There are obviosuly some style issues and verbose code (`public` on interface methods) but I'm not going to pick at your code when I can easily fix it. Most of it follows the style. I am going to merge into a seperate branch first and then back into main.

**Comment by MrCrayfish** [comment]
It'll be a while before this is public since I want to 1.18 to be feature parity.

**Comment by Speiger** [comment]
Yeah that would be awesome. Sry that I added so much extra work.

**Comment by Speiger** [comment]
@MrCrayfish while this topic is over.
Just wanted to thank you again that you added this patch.

Now thanks to that IC2C, just in time can have configured support!

**Comment by Speiger** [comment]
image

**Comment by MrCrayfish** [comment]
Hey @Speiger, I am currently relicensing Configured. I want to change the mod to be under a more appropriate license of LGPLv3.
I want to get your permission to change the license of your contributions under this new license. Thank you.

**Comment by Speiger** [comment]
@MrCrayfish I don't see much of a problem with that.
So yeah go ahead with that :)

**Comment by MrCrayfish** [comment]
Thank you for the quick response.

**Comment by Speiger** [comment]
@MrCrayfish why are you going LGPLv3?
Is that something you discuss in public?

**Comment by MrCrayfish** [comment]
@Speiger To continue copyleft and to give addon mods more freedom over their licensing.

**Comment by Speiger** [comment]
@MrCrayfish huh.
Not sure if LGPL3 is really the best license for it. Assuming you want to also allow closed source projects to use this for a compat.
But on the other hand who am I to judge.

It's not like I haven't replaced configured for all my mods already.
But yeah I hope that it helps you out :)

**Comment by MrCrayfish** [comment]
Correct me if I'm wrong, Isn't the point of LPGL to allow works to link into a software without being affected by the license? E.g Forge is LPGLv2.1 but you can create a mod for it under any license.

**Comment by Speiger** [comment]
It "should" but the LPG/L licenses are always difficult to interpret based on what you can and can not do.
At least to my experience.

**Pull request merged**
