### PR TITLE
Improve Chinese (Simplified) translation

### PR DESCRIPTION
**Pull request by jellybean13**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Hey @jellybean13, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

**Comment by jellybean13** [comment]
> Hey @jellybean13, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

Of course you can. What can I do for you?

**Comment by MrCrayfish** [comment]
Sorry, I made a mistake. When I referred to contributions, I mean your contributions to this repo. Can I get your permission to relicense them to LGPLv3?

**Comment by jellybean13** [comment]
> Sorry, I made a mistake. When I referred to contributions, I mean your contributions to this repo. Can I get your permission to relicense them to LGPLv3?

Yes, you can.

**Comment by MrCrayfish** [comment]
Thank you and I appreciate your efforts to improve the mod.

**Pull request merged**
