### PR TITLE
Update Japanese translation.

### PR DESCRIPTION
**Pull request by fltuna**
Update ja_jp.json with full translation.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @faketuna, I am currently relicensing Configured to LGPLv3. I want to get your permission to change contributions under this new license. Thank you.

**Comment by fltuna** [comment]
Sure. go ahead! thank you for letting me know!

**Comment by MrCrayfish** [comment]
Thanks for the quick response.

**Comment by MrCrayfish** [comment]
I just want to clarify when I said contributions in the initial message, I meant your contributions. I just want to clear this up.

**Pull request merged**
