### PR TITLE
Update it_it.json

### PR DESCRIPTION
**Pull request by SimGitHub5**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @SimGitHub5, I am currently relicensing Configured to LGPLv3. I want to get your permission to change your contributions under this new license. Thank you.

**Comment by ghost** [comment]
> Hey @SimGitHub5, I am currently relicensing Configured to LGPLv3. I want to get your permission to change your contributions under this new license. Thank you.

Yes, I grant you permission to change my contributions under this new license. Yw! (I'm SimGitHub5).

**Comment by MrCrayfish** [comment]
Thank you.

**Pull request merged**
